services:
  - type: web
    name: team-taraba-river-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/server.cjs
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: service-account.json
      - key: OWNER_EMAIL
        value: tarabateam@gmail.com
      - key: ADMIN_EMAILS
        value: tarabateam@gmail.com,kefox.nwoko@gmail.com
      - key: CRON_SECRET
        value: c142a7b54f76c5d3bc02035a32559c3073202fb9056c8d5b
